apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-store
  name: object-store
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: object-store